name: notes_3d
description: A responsive 3D notes application using Flutter, Firebase and MVVM.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  cloud_firestore: ^6.10.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#EEF2FF"
    theme_color: "#6C4DF6"

  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 256