// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgTWTt1nxqdUDSDTnWHVaTje51JtALRTg',
    appId: '1:529473229422:web:98b7b3a48a68e789a9cc7f',
    messagingSenderId: '529473229422',
    projectId: 'notes-3d',
    authDomain: 'notes-3d.firebaseapp.com',
    storageBucket: 'notes-3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa82xPJ4pBvYiI7OcHkp2NpVZo2fJ4PPo',
    appId: '1:529473229422:android:ebc0a12e6e9b10d3a9cc7f',
    messagingSenderId: '529473229422',
    projectId: 'notes-3d',
    storageBucket: 'notes-3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIaKGSSh_yuk-pZ8tz9NzBrmxGhKlUQEg',
    appId: '1:529473229422:ios:92e3d763d0e24173a9cc7f',
    messagingSenderId: '529473229422',
    projectId: 'notes-3d',
    storageBucket: 'notes-3d.firebasestorage.app',
    iosBundleId: 'com.example.notes3d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIaKGSSh_yuk-pZ8tz9NzBrmxGhKlUQEg',
    appId: '1:529473229422:ios:92e3d763d0e24173a9cc7f',
    messagingSenderId: '529473229422',
    projectId: 'notes-3d',
    storageBucket: 'notes-3d.firebasestorage.app',
    iosBundleId: 'com.example.notes3d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgTWTt1nxqdUDSDTnWHVaTje51JtALRTg',
    appId: '1:529473229422:web:03872162ef4cdeb8a9cc7f',
    messagingSenderId: '529473229422',
    projectId: 'notes-3d',
    authDomain: 'notes-3d.firebaseapp.com',
    storageBucket: 'notes-3d.firebasestorage.app',
  );
}
